package com.airiea.knowledge.model.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "knowledge")
public class KnowledgeDAO {
    @DynamoDBHashKey(attributeName = "knowledge_id")
    @JsonProperty("knowledge_id")
    String knowledgeId;

    @DynamoDBIndexHashKey(attributeName = "agent_name", globalSecondaryIndexName = "agent_name-entity_id")
    @JsonProperty("agent_name")
    String agentName;

    @DynamoDBIndexRangeKey(attributeName = "entity_id", globalSecondaryIndexName = "agent_name-entity_id")
    @JsonProperty("entity_id")
    String entityId;

    @DynamoDBAttribute(attributeName = "content")
    String content;

    @DynamoDBAttribute(attributeName = "embedding")
    List<Double> embedding;

    @DynamoDBAttribute(attributeName = "is_updating")
    @JsonProperty("is_updating")
    Boolean isUpdating;

    @DynamoDBAttribute(attributeName = "update_type")
    @JsonProperty("update_type")
    String updateType;

    @JsonProperty("update_delimiter")
    @DynamoDBAttribute(attributeName = "update_delimiter")
    String updateDelimiter;

    @JsonProperty("created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    Date createdDate;

    @JsonProperty("updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    Date updatedDate;
}
